/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

/**
 * @summary Get workspace by ID
 */
export const GetByIdParams = zod.object({
  "id": zod.uuid()
})

export const GetByIdResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "description": zod.string(),
  "ownerId": zod.string(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})


/**
 * @summary Update an existing workspace
 */
export const UpdateParams = zod.object({
  "id": zod.uuid()
})

export const updateBodyNameMax = 255;

export const updateBodyDescriptionMin = 0;
export const updateBodyDescriptionMax = 1000;



export const UpdateBody = zod.object({
  "name": zod.string().min(1).max(updateBodyNameMax).optional(),
  "description": zod.string().min(updateBodyDescriptionMin).max(updateBodyDescriptionMax).optional()
})

export const UpdateResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "description": zod.string(),
  "ownerId": zod.string(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})


/**
 * @summary Delete a workspace by ID
 */
export const _DeleteParams = zod.object({
  "id": zod.uuid()
})


export const TransferOwnershipParams = zod.object({
  "id": zod.uuid()
})

export const TransferOwnershipQueryParams = zod.object({
  "newOwnerId": zod.string()
})


/**
 * @summary List workspaces with pagination and optional search
 */
export const listQueryPageDefault = 1;
export const listQuerySizeDefault = 20;

export const ListQueryParams = zod.object({
  "page": zod.number().default(listQueryPageDefault),
  "size": zod.number().default(listQuerySizeDefault),
  "search": zod.string().optional()
})

export const ListResponse = zod.object({
  "content": zod.array(zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "description": zod.string(),
  "ownerId": zod.string(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})).optional(),
  "totalElements": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional()
})


/**
 * @summary Create a new workspace
 */
export const createBodyNameMin = 0;
export const createBodyNameMax = 255;

export const createBodyDescriptionMin = 0;
export const createBodyDescriptionMax = 1000;



export const CreateBody = zod.object({
  "name": zod.string().min(createBodyNameMin).max(createBodyNameMax),
  "description": zod.string().min(createBodyDescriptionMin).max(createBodyDescriptionMax).optional()
})

export const CreateResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "description": zod.string(),
  "ownerId": zod.string(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})


export const GetMembersParams = zod.object({
  "id": zod.uuid()
})

export const GetMembersResponse = zod.object({
  "members": zod.array(zod.object({
  "id": zod.uuid().optional(),
  "userId": zod.email(),
  "role": zod.enum(['OWNER', 'EDITOR', 'READER', 'UNRECOGNIZED'])
})).optional()
})
