/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

/**
 * @summary Get workspace by ID
 */
export const getByIdParams = zod.object({
  "id": zod.string().uuid()
})


/**
 * @summary Update an existing workspace
 */
export const updateParams = zod.object({
  "id": zod.string().uuid()
})

export const updateBodyNameMax = 255;

export const updateBodyDescriptionMin = 0;
export const updateBodyDescriptionMax = 1000;



export const updateBody = zod.object({
  "name": zod.string().min(1).max(updateBodyNameMax).optional(),
  "description": zod.string().min(updateBodyDescriptionMin).max(updateBodyDescriptionMax).optional()
})


/**
 * @summary Delete a workspace by ID
 */
export const _deleteParams = zod.object({
  "id": zod.string().uuid()
})


export const transferOwnershipParams = zod.object({
  "id": zod.string().uuid()
})

export const transferOwnershipQueryParams = zod.object({
  "newOwnerId": zod.string()
})


/**
 * @summary List workspaces with pagination and optional search
 */
export const listQueryPageDefault = 1;export const listQuerySizeDefault = 20;

export const listQueryParams = zod.object({
  "page": zod.number().default(listQueryPageDefault),
  "size": zod.number().default(listQuerySizeDefault),
  "search": zod.string().optional()
})


/**
 * @summary Create a new workspace
 */
export const createBodyNameMin = 0;
export const createBodyNameMax = 255;

export const createBodyDescriptionMin = 0;
export const createBodyDescriptionMax = 1000;



export const createBody = zod.object({
  "name": zod.string().min(createBodyNameMin).max(createBodyNameMax),
  "description": zod.string().min(createBodyDescriptionMin).max(createBodyDescriptionMax).optional()
})


export const getMembersParams = zod.object({
  "id": zod.string().uuid()
})
