/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const verifyEmailBodyCodeMin = 6;
export const verifyEmailBodyCodeMax = 6;



export const verifyEmailBody = zod.object({
  "email": zod.string(),
  "code": zod.string().min(verifyEmailBodyCodeMin).max(verifyEmailBodyCodeMax)
})


export const resendVerificationBodyCodeMin = 6;
export const resendVerificationBodyCodeMax = 6;



export const resendVerificationBody = zod.object({
  "email": zod.string(),
  "code": zod.string().min(resendVerificationBodyCodeMin).max(resendVerificationBodyCodeMax)
})


export const createUserBody = zod.object({
  "email": zod.string()
})


export const updateUserBody = zod.object({
  "name": zod.string().optional()
})
