/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const verifyEmailBodyCodeMin = 6;
export const verifyEmailBodyCodeMax = 6;



export const VerifyEmailBody = zod.object({
  "email": zod.string(),
  "code": zod.string().min(verifyEmailBodyCodeMin).max(verifyEmailBodyCodeMax)
})


export const resendVerificationBodyCodeMin = 6;
export const resendVerificationBodyCodeMax = 6;



export const ResendVerificationBody = zod.object({
  "email": zod.string(),
  "code": zod.string().min(resendVerificationBodyCodeMin).max(resendVerificationBodyCodeMax)
})


export const GetUserResponse = zod.object({
  "name": zod.string().optional(),
  "email": zod.string().optional(),
  "avatarUrl": zod.string().optional(),
  "verified": zod.boolean().optional()
})


export const CreateUserBody = zod.object({
  "email": zod.string()
})


export const UpdateUserBody = zod.object({
  "name": zod.string().optional()
})

export const UpdateUserResponse = zod.object({
  "name": zod.string().optional(),
  "email": zod.string().optional(),
  "avatarUrl": zod.string().optional(),
  "verified": zod.boolean().optional()
})
