/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const createUserBody = zod.object({
  "name": zod.string().min(1)
})





export const updateUserBody = zod.object({
  "name": zod.string().min(1)
})
