/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface BlockDto {
  id?: string;
  type: string;
  content?: BlockDto[];
  attrs?: string;
  text?: string;
}

export interface BlockSnapshotRequest {
  version?: number;
  schemaVersion?: number;
  updatedAt?: string;
  updatedBy?: string;
  source?: string;
  content?: BlockDto;
}

export interface PageRequest {
  /** @minLength 1 */
  title: string;
  icon?: string;
}

export interface PageResponse {
  id: string;
  workspaceId: string;
  title: string;
  icon: string;
  createdAt: string;
  updatedAt: string;
}

export interface BlockTreeNodeDto {
  id?: string;
  parentId?: string;
  type?: string;
  position?: string;
  content?: JsonNode;
  attrs?: JsonNode;
  /** Child blocks */
  children?: BlockTreeNodeDto;
}

export interface DocumentTreeResponse {
  documentId?: string;
  version?: number;
  blocks?: BlockTreeNodeDto[];
}

export interface JsonNode {}

export const getOpenAPIDefinition = () => {
const saveSnapshot = <TData = AxiosResponse<void>>(
    documentId: string,
    blockSnapshotRequest: BlockSnapshotRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://ckw-page-service:8080/internal/documents/${documentId}/snapshot`,
      blockSnapshotRequest,options
    );
  }

const getPages = <TData = AxiosResponse<PageResponse[]>>(
    workspaceId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://ckw-page-service:8080/${workspaceId}/documents`,options
    );
  }

const createPage = <TData = AxiosResponse<PageResponse>>(
    workspaceId: string,
    pageRequest: PageRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://ckw-page-service:8080/${workspaceId}/documents`,
      pageRequest,options
    );
  }

const getPage = <TData = AxiosResponse<PageResponse>>(
    workspaceId: string,
    pageId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://ckw-page-service:8080/${workspaceId}/documents/${pageId}`,options
    );
  }

const deletePage = <TData = AxiosResponse<void>>(
    workspaceId: string,
    pageId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `http://ckw-page-service:8080/${workspaceId}/documents/${pageId}`,options
    );
  }

const updatePage = <TData = AxiosResponse<PageResponse>>(
    workspaceId: string,
    pageId: string,
    pageRequest: PageRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `http://ckw-page-service:8080/${workspaceId}/documents/${pageId}`,
      pageRequest,options
    );
  }

const getTree = <TData = AxiosResponse<DocumentTreeResponse>>(
    workspaceId: string,
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://ckw-page-service:8080/${workspaceId}/documents/${id}/tree`,options
    );
  }

return {saveSnapshot,getPages,createPage,getPage,deletePage,updatePage,getTree}};
export type SaveSnapshotResult = AxiosResponse<void>
export type GetPagesResult = AxiosResponse<PageResponse[]>
export type CreatePageResult = AxiosResponse<PageResponse>
export type GetPageResult = AxiosResponse<PageResponse>
export type DeletePageResult = AxiosResponse<void>
export type UpdatePageResult = AxiosResponse<PageResponse>
export type GetTreeResult = AxiosResponse<DocumentTreeResponse>
