/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface BlockDto {
  type: string;
  content?: BlockDto[];
  attrs?: string;
  marks?: string;
  text?: string;
}

export interface BlockSnapshotRequest {
  version?: number;
  schemaVersion?: number;
  generatedAt?: string;
  updatedBy?: string;
  source?: string;
  content?: BlockDto;
}

export interface DocumentRequest {
  /** @minLength 1 */
  title: string;
  icon?: string;
}

export interface DocumentResponse {
  id: string;
  workspaceId: string;
  title: string;
  icon: string;
  directoryId?: string;
  sortOrder?: number;
  createdAt: string;
  updatedAt: string;
}

export interface DirectoryRequest {
  /**
   * @minLength 0
   * @maxLength 255
   */
  name: string;
  parentId?: string;
  sortOrder?: number;
}

export interface DirectoryResponse {
  id?: string;
  workspaceId?: string;
  parentId?: string;
  name?: string;
  sortOrder?: number;
  createdAt?: string;
}

export interface MovePageRequest {
  directoryId?: string;
  sortOrder?: number;
}

export interface SnapshotResponse {
  version?: number;
  schemaVersion?: number;
  generatedAt?: string;
  updatedBy?: string;
  source?: string;
  contentJson?: string;
}

export type GetSnapshot404 = {[key: string]: string};

export type SaveSnapshot404 = {[key: string]: string};

export type GetPages404 = {[key: string]: string};

export type CreatePage404 = {[key: string]: string};

export type ListDirectories404 = {[key: string]: string};

export type CreateDirectory404 = {[key: string]: string};

export type MovePage404 = {[key: string]: string};

export type GetPage404 = {[key: string]: string};

export type DeletePage404 = {[key: string]: string};

export type UpdatePage404 = {[key: string]: string};

export type DeleteDirectory404 = {[key: string]: string};

export type UpdateDirectory404 = {[key: string]: string};

export const getOpenAPIDefinition = (axiosInstance: AxiosInstance = axios.default) => {
const getSnapshot = (
    documentId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SnapshotResponse>> => {
    return axiosInstance.get(
      `/internal/documents/${documentId}/snapshot`,options
    );
  }

const saveSnapshot = (
    documentId: string,
    blockSnapshotRequest: BlockSnapshotRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(
      `/internal/documents/${documentId}/snapshot`,
      blockSnapshotRequest,options
    );
  }

const getPages = (
    workspaceId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentResponse[]>> => {
    return axiosInstance.get(
      `/${workspaceId}/documents`,options
    );
  }

const createPage = (
    workspaceId: string,
    documentRequest: DocumentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentResponse>> => {
    return axiosInstance.post(
      `/${workspaceId}/documents`,
      documentRequest,options
    );
  }

const listDirectories = (
    workspaceId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DirectoryResponse[]>> => {
    return axiosInstance.get(
      `/${workspaceId}/directories`,options
    );
  }

const createDirectory = (
    workspaceId: string,
    directoryRequest: DirectoryRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DirectoryResponse>> => {
    return axiosInstance.post(
      `/${workspaceId}/directories`,
      directoryRequest,options
    );
  }

const movePage = (
    workspaceId: string,
    pageId: string,
    movePageRequest: MovePageRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentResponse>> => {
    return axiosInstance.patch(
      `/${workspaceId}/documents/${pageId}/move`,
      movePageRequest,options
    );
  }

const getPage = (
    workspaceId: string,
    pageId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentResponse>> => {
    return axiosInstance.get(
      `/${workspaceId}/documents/${pageId}`,options
    );
  }

const deletePage = (
    workspaceId: string,
    pageId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/${workspaceId}/documents/${pageId}`,options
    );
  }

const updatePage = (
    workspaceId: string,
    pageId: string,
    documentRequest: DocumentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentResponse>> => {
    return axiosInstance.patch(
      `/${workspaceId}/documents/${pageId}`,
      documentRequest,options
    );
  }

const deleteDirectory = (
    workspaceId: string,
    directoryId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/${workspaceId}/directories/${directoryId}`,options
    );
  }

const updateDirectory = (
    workspaceId: string,
    directoryId: string,
    directoryRequest: DirectoryRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DirectoryResponse>> => {
    return axiosInstance.patch(
      `/${workspaceId}/directories/${directoryId}`,
      directoryRequest,options
    );
  }

return {getSnapshot,saveSnapshot,getPages,createPage,listDirectories,createDirectory,movePage,getPage,deletePage,updatePage,deleteDirectory,updateDirectory}};
export type GetSnapshotResult = AxiosResponse<SnapshotResponse>
export type SaveSnapshotResult = AxiosResponse<void>
export type GetPagesResult = AxiosResponse<DocumentResponse[]>
export type CreatePageResult = AxiosResponse<DocumentResponse>
export type ListDirectoriesResult = AxiosResponse<DirectoryResponse[]>
export type CreateDirectoryResult = AxiosResponse<DirectoryResponse>
export type MovePageResult = AxiosResponse<DocumentResponse>
export type GetPageResult = AxiosResponse<DocumentResponse>
export type DeletePageResult = AxiosResponse<void>
export type UpdatePageResult = AxiosResponse<DocumentResponse>
export type DeleteDirectoryResult = AxiosResponse<void>
export type UpdateDirectoryResult = AxiosResponse<DirectoryResponse>
