/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface PageRequest {
  /** @minLength 1 */
  title: string;
  icon?: string;
}

export interface PageResponse {
  id: string;
  workspaceId: string;
  title: string;
  icon: string;
  createdAt: string;
  updatedAt: string;
}

export type BlockRequestType = typeof BlockRequestType[keyof typeof BlockRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlockRequestType = {
  PARAGRAPH: 'PARAGRAPH',
  HEADING_1: 'HEADING_1',
  HEADING_2: 'HEADING_2',
  HEADING_3: 'HEADING_3',
  BULLET_LIST: 'BULLET_LIST',
  NUMBER_LIST: 'NUMBER_LIST',
  TODO: 'TODO',
  IMAGE: 'IMAGE',
  CODE: 'CODE',
  CALLOUT: 'CALLOUT',
  DIVIDER: 'DIVIDER',
  DOCUMENT: 'DOCUMENT',
} as const;

export interface BlockRequest {
  parentId: string;
  type: BlockRequestType;
  contentJson: string;
  orderIndex: number;
}

export type BlockResponseType = typeof BlockResponseType[keyof typeof BlockResponseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlockResponseType = {
  PARAGRAPH: 'PARAGRAPH',
  HEADING_1: 'HEADING_1',
  HEADING_2: 'HEADING_2',
  HEADING_3: 'HEADING_3',
  BULLET_LIST: 'BULLET_LIST',
  NUMBER_LIST: 'NUMBER_LIST',
  TODO: 'TODO',
  IMAGE: 'IMAGE',
  CODE: 'CODE',
  CALLOUT: 'CALLOUT',
  DIVIDER: 'DIVIDER',
  DOCUMENT: 'DOCUMENT',
} as const;

export interface BlockResponse {
  id: string;
  pageId: string;
  parentId?: string;
  type: BlockResponseType;
  contentJson: string;
  orderIndex: number;
  createdAt: string;
  updatedAt: string;
}

export const getOpenAPIDefinition = () => {
const getPages = <TData = AxiosResponse<PageResponse[]>>(
    workspaceId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/${workspaceId}/pages`,options
    );
  }

const createPage = <TData = AxiosResponse<PageResponse>>(
    workspaceId: string,
    pageRequest: PageRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:8080/${workspaceId}/pages`,
      pageRequest,options
    );
  }

const getBlocks = <TData = AxiosResponse<BlockResponse[]>>(
    workspaceId: string,
    pageId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/${workspaceId}/pages/${pageId}/blocks`,options
    );
  }

const createBlock = <TData = AxiosResponse<BlockResponse>>(
    workspaceId: string,
    pageId: string,
    blockRequest: BlockRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:8080/${workspaceId}/pages/${pageId}/blocks`,
      blockRequest,options
    );
  }

const getPage = <TData = AxiosResponse<PageResponse>>(
    workspaceId: string,
    pageId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8080/${workspaceId}/pages/${pageId}`,options
    );
  }

const deletePage = <TData = AxiosResponse<void>>(
    workspaceId: string,
    pageId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:8080/${workspaceId}/pages/${pageId}`,options
    );
  }

const updatePage = <TData = AxiosResponse<PageResponse>>(
    workspaceId: string,
    pageId: string,
    pageRequest: PageRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `http://localhost:8080/${workspaceId}/pages/${pageId}`,
      pageRequest,options
    );
  }

const deleteBlock = <TData = AxiosResponse<void>>(
    workspaceId: string,
    pageId: string,
    blockId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:8080/${workspaceId}/pages/${pageId}/blocks/${blockId}`,options
    );
  }

const updateBlock = <TData = AxiosResponse<BlockResponse>>(
    workspaceId: string,
    pageId: string,
    blockId: string,
    blockRequest: BlockRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `http://localhost:8080/${workspaceId}/pages/${pageId}/blocks/${blockId}`,
      blockRequest,options
    );
  }

return {getPages,createPage,getBlocks,createBlock,getPage,deletePage,updatePage,deleteBlock,updateBlock}};
export type GetPagesResult = AxiosResponse<PageResponse[]>
export type CreatePageResult = AxiosResponse<PageResponse>
export type GetBlocksResult = AxiosResponse<BlockResponse[]>
export type CreateBlockResult = AxiosResponse<BlockResponse>
export type GetPageResult = AxiosResponse<PageResponse>
export type DeletePageResult = AxiosResponse<void>
export type UpdatePageResult = AxiosResponse<PageResponse>
export type DeleteBlockResult = AxiosResponse<void>
export type UpdateBlockResult = AxiosResponse<BlockResponse>
