import type {ProseMirrorDoc} from "./ProseMirrorDoc.ts";

export interface PageSnapshotV1 {
    /** Schema version for future evolution */
    schemaVersion: 1

    /** Page / document identity */
    pageId: string

    /** Monotonic version generated by collaboration service */
    version: number

    /** ISO timestamp when snapshot was produced */
    generatedAt: string

    /** User who caused the last change (best effort) */
    updatedBy?: string

    /** Source of truth */
    source: 'collaboration-service'

    /** Normalized ProseMirror JSON */
    content: ProseMirrorDoc
}
