apiVersion: v1
kind: Secret
metadata:
  name: page-service-secrets
type: Opaque
data:
  # Base64 encoded values
  SPRING_R2DBC_PASSWORD: <PASSWORD>
  SPRING_R2DBC_USERNAME: <USERNAME>
  SPRING_R2DBC_URL: <URL>
