/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface BlockDto {
  type: string;
  content?: BlockDto[];
  attrs?: string;
  marks?: string;
  text?: string;
}

export interface BlockSnapshotRequest {
  version?: number;
  schemaVersion?: number;
  generatedAt?: string;
  updatedBy?: string;
  source?: string;
  content?: BlockDto;
}

export interface DocumentRequest {
  /** @minLength 1 */
  title: string;
  icon?: string;
}

export interface DocumentResponse {
  id: string;
  workspaceId: string;
  title: string;
  icon: string;
  createdAt: string;
  updatedAt: string;
}

export interface SnapshotResponse {
  version?: number;
  schemaVersion?: number;
  generatedAt?: string;
  updatedBy?: string;
  source?: string;
  contentJson?: string;
}

export const getSnapshot = (
    documentId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SnapshotResponse>> => {
    
    
    return axios.default.get(
      `http://localhost:8080/workspace/internal/documents/${documentId}/snapshot`,options
    );
  }




export const getGetSnapshotQueryKey = (documentId?: string,) => {
    return [
    `http://localhost:8080/workspace/internal/documents/${documentId}/snapshot`
    ] as const;
    }

    
export const getGetSnapshotQueryOptions = <TData = Awaited<ReturnType<typeof getSnapshot>>, TError = AxiosError<string>>(documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSnapshotQueryKey(documentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSnapshot>>> = ({ signal }) => getSnapshot(documentId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(documentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSnapshotQueryResult = NonNullable<Awaited<ReturnType<typeof getSnapshot>>>
export type GetSnapshotQueryError = AxiosError<string>


export function useGetSnapshot<TData = Awaited<ReturnType<typeof getSnapshot>>, TError = AxiosError<string>>(
 documentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSnapshot>>,
          TError,
          Awaited<ReturnType<typeof getSnapshot>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSnapshot<TData = Awaited<ReturnType<typeof getSnapshot>>, TError = AxiosError<string>>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSnapshot>>,
          TError,
          Awaited<ReturnType<typeof getSnapshot>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSnapshot<TData = Awaited<ReturnType<typeof getSnapshot>>, TError = AxiosError<string>>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSnapshot<TData = Awaited<ReturnType<typeof getSnapshot>>, TError = AxiosError<string>>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSnapshotQueryOptions(documentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const saveSnapshot = (
    documentId: string,
    blockSnapshotRequest: BlockSnapshotRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.put(
      `http://localhost:8080/workspace/internal/documents/${documentId}/snapshot`,
      blockSnapshotRequest,options
    );
  }



export const getSaveSnapshotMutationOptions = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveSnapshot>>, TError,{documentId: string;data: BlockSnapshotRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof saveSnapshot>>, TError,{documentId: string;data: BlockSnapshotRequest}, TContext> => {

const mutationKey = ['saveSnapshot'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saveSnapshot>>, {documentId: string;data: BlockSnapshotRequest}> = (props) => {
          const {documentId,data} = props ?? {};

          return  saveSnapshot(documentId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SaveSnapshotMutationResult = NonNullable<Awaited<ReturnType<typeof saveSnapshot>>>
    export type SaveSnapshotMutationBody = BlockSnapshotRequest
    export type SaveSnapshotMutationError = AxiosError<string>

    export const useSaveSnapshot = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveSnapshot>>, TError,{documentId: string;data: BlockSnapshotRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saveSnapshot>>,
        TError,
        {documentId: string;data: BlockSnapshotRequest},
        TContext
      > => {

      const mutationOptions = getSaveSnapshotMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getPages = (
    workspaceId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentResponse[]>> => {
    
    
    return axios.default.get(
      `http://localhost:8080/workspace/${workspaceId}/documents`,options
    );
  }




export const getGetPagesQueryKey = (workspaceId?: string,) => {
    return [
    `http://localhost:8080/workspace/${workspaceId}/documents`
    ] as const;
    }

    
export const getGetPagesQueryOptions = <TData = Awaited<ReturnType<typeof getPages>>, TError = AxiosError<string>>(workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPagesQueryKey(workspaceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPages>>> = ({ signal }) => getPages(workspaceId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPagesQueryResult = NonNullable<Awaited<ReturnType<typeof getPages>>>
export type GetPagesQueryError = AxiosError<string>


export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = AxiosError<string>>(
 workspaceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPages>>,
          TError,
          Awaited<ReturnType<typeof getPages>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = AxiosError<string>>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPages>>,
          TError,
          Awaited<ReturnType<typeof getPages>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = AxiosError<string>>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = AxiosError<string>>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPagesQueryOptions(workspaceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const createPage = (
    workspaceId: string,
    documentRequest: DocumentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentResponse>> => {
    
    
    return axios.default.post(
      `http://localhost:8080/workspace/${workspaceId}/documents`,
      documentRequest,options
    );
  }



export const getCreatePageMutationOptions = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPage>>, TError,{workspaceId: string;data: DocumentRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createPage>>, TError,{workspaceId: string;data: DocumentRequest}, TContext> => {

const mutationKey = ['createPage'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPage>>, {workspaceId: string;data: DocumentRequest}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  createPage(workspaceId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePageMutationResult = NonNullable<Awaited<ReturnType<typeof createPage>>>
    export type CreatePageMutationBody = DocumentRequest
    export type CreatePageMutationError = AxiosError<string>

    export const useCreatePage = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPage>>, TError,{workspaceId: string;data: DocumentRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPage>>,
        TError,
        {workspaceId: string;data: DocumentRequest},
        TContext
      > => {

      const mutationOptions = getCreatePageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getPage = (
    workspaceId: string,
    pageId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentResponse>> => {
    
    
    return axios.default.get(
      `http://localhost:8080/workspace/${workspaceId}/documents/${pageId}`,options
    );
  }




export const getGetPageQueryKey = (workspaceId?: string,
    pageId?: string,) => {
    return [
    `http://localhost:8080/workspace/${workspaceId}/documents/${pageId}`
    ] as const;
    }

    
export const getGetPageQueryOptions = <TData = Awaited<ReturnType<typeof getPage>>, TError = AxiosError<string>>(workspaceId: string,
    pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPageQueryKey(workspaceId,pageId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPage>>> = ({ signal }) => getPage(workspaceId,pageId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId && pageId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPageQueryResult = NonNullable<Awaited<ReturnType<typeof getPage>>>
export type GetPageQueryError = AxiosError<string>


export function useGetPage<TData = Awaited<ReturnType<typeof getPage>>, TError = AxiosError<string>>(
 workspaceId: string,
    pageId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPage>>,
          TError,
          Awaited<ReturnType<typeof getPage>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPage<TData = Awaited<ReturnType<typeof getPage>>, TError = AxiosError<string>>(
 workspaceId: string,
    pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPage>>,
          TError,
          Awaited<ReturnType<typeof getPage>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPage<TData = Awaited<ReturnType<typeof getPage>>, TError = AxiosError<string>>(
 workspaceId: string,
    pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPage<TData = Awaited<ReturnType<typeof getPage>>, TError = AxiosError<string>>(
 workspaceId: string,
    pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPageQueryOptions(workspaceId,pageId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const deletePage = (
    workspaceId: string,
    pageId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `http://localhost:8080/workspace/${workspaceId}/documents/${pageId}`,options
    );
  }



export const getDeletePageMutationOptions = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePage>>, TError,{workspaceId: string;pageId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deletePage>>, TError,{workspaceId: string;pageId: string}, TContext> => {

const mutationKey = ['deletePage'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePage>>, {workspaceId: string;pageId: string}> = (props) => {
          const {workspaceId,pageId} = props ?? {};

          return  deletePage(workspaceId,pageId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePageMutationResult = NonNullable<Awaited<ReturnType<typeof deletePage>>>
    
    export type DeletePageMutationError = AxiosError<string>

    export const useDeletePage = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePage>>, TError,{workspaceId: string;pageId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePage>>,
        TError,
        {workspaceId: string;pageId: string},
        TContext
      > => {

      const mutationOptions = getDeletePageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const updatePage = (
    workspaceId: string,
    pageId: string,
    documentRequest: DocumentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DocumentResponse>> => {
    
    
    return axios.default.patch(
      `http://localhost:8080/workspace/${workspaceId}/documents/${pageId}`,
      documentRequest,options
    );
  }



export const getUpdatePageMutationOptions = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePage>>, TError,{workspaceId: string;pageId: string;data: DocumentRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updatePage>>, TError,{workspaceId: string;pageId: string;data: DocumentRequest}, TContext> => {

const mutationKey = ['updatePage'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePage>>, {workspaceId: string;pageId: string;data: DocumentRequest}> = (props) => {
          const {workspaceId,pageId,data} = props ?? {};

          return  updatePage(workspaceId,pageId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePageMutationResult = NonNullable<Awaited<ReturnType<typeof updatePage>>>
    export type UpdatePageMutationBody = DocumentRequest
    export type UpdatePageMutationError = AxiosError<string>

    export const useUpdatePage = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePage>>, TError,{workspaceId: string;pageId: string;data: DocumentRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePage>>,
        TError,
        {workspaceId: string;pageId: string;data: DocumentRequest},
        TContext
      > => {

      const mutationOptions = getUpdatePageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
