/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../lib/axios';
import type { ErrorType , BodyType } from '../../lib/axios';
export interface BlockDto {
  type: string;
  content?: BlockDto[];
  attrs?: string;
  marks?: string;
  text?: string;
}

export interface BlockSnapshotRequest {
  version?: number;
  schemaVersion?: number;
  generatedAt?: string;
  updatedBy?: string;
  source?: string;
  content?: BlockDto;
}

export interface DocumentRequest {
  /** @minLength 1 */
  title: string;
  icon?: string;
}

export interface DocumentResponse {
  id: string;
  workspaceId: string;
  title: string;
  icon: string;
  directoryId?: string;
  sortOrder?: number;
  createdAt: string;
  updatedAt: string;
}

export interface DirectoryRequest {
  /**
   * @minLength 0
   * @maxLength 255
   */
  name: string;
  parentId?: string;
  sortOrder?: number;
}

export interface DirectoryResponse {
  id?: string;
  workspaceId?: string;
  parentId?: string;
  name?: string;
  sortOrder?: number;
  createdAt?: string;
}

export interface MovePageRequest {
  directoryId?: string;
  sortOrder?: number;
}

export interface SnapshotResponse {
  version?: number;
  schemaVersion?: number;
  generatedAt?: string;
  updatedBy?: string;
  source?: string;
  contentJson?: string;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getSnapshot = (
    documentId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SnapshotResponse>(
      {url: `/workspace/internal/documents/${documentId}/snapshot`, method: 'GET', signal
    },
      options);
    }
  



export const getGetSnapshotQueryKey = (documentId: string,) => {
    return [
    `/workspace/internal/documents/${documentId}/snapshot`
    ] as const;
    }

    
export const getGetSnapshotQueryOptions = <TData = Awaited<ReturnType<typeof getSnapshot>>, TError = ErrorType<Blob>>(documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSnapshotQueryKey(documentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSnapshot>>> = ({ signal }) => getSnapshot(documentId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(documentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSnapshotQueryResult = NonNullable<Awaited<ReturnType<typeof getSnapshot>>>
export type GetSnapshotQueryError = ErrorType<Blob>


export function useGetSnapshot<TData = Awaited<ReturnType<typeof getSnapshot>>, TError = ErrorType<Blob>>(
 documentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSnapshot>>,
          TError,
          Awaited<ReturnType<typeof getSnapshot>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSnapshot<TData = Awaited<ReturnType<typeof getSnapshot>>, TError = ErrorType<Blob>>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSnapshot>>,
          TError,
          Awaited<ReturnType<typeof getSnapshot>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSnapshot<TData = Awaited<ReturnType<typeof getSnapshot>>, TError = ErrorType<Blob>>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSnapshot<TData = Awaited<ReturnType<typeof getSnapshot>>, TError = ErrorType<Blob>>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSnapshot>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSnapshotQueryOptions(documentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const saveSnapshot = (
    documentId: string,
    blockSnapshotRequest: BodyType<BlockSnapshotRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/workspace/internal/documents/${documentId}/snapshot`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: blockSnapshotRequest, signal
    },
      options);
    }
  


export const getSaveSnapshotMutationOptions = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveSnapshot>>, TError,{documentId: string;data: BodyType<BlockSnapshotRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof saveSnapshot>>, TError,{documentId: string;data: BodyType<BlockSnapshotRequest>}, TContext> => {

const mutationKey = ['saveSnapshot'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saveSnapshot>>, {documentId: string;data: BodyType<BlockSnapshotRequest>}> = (props) => {
          const {documentId,data} = props ?? {};

          return  saveSnapshot(documentId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SaveSnapshotMutationResult = NonNullable<Awaited<ReturnType<typeof saveSnapshot>>>
    export type SaveSnapshotMutationBody = BodyType<BlockSnapshotRequest>
    export type SaveSnapshotMutationError = ErrorType<Blob>

    export const useSaveSnapshot = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveSnapshot>>, TError,{documentId: string;data: BodyType<BlockSnapshotRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saveSnapshot>>,
        TError,
        {documentId: string;data: BodyType<BlockSnapshotRequest>},
        TContext
      > => {
      return useMutation(getSaveSnapshotMutationOptions(options), queryClient);
    }
    
export const getPages = (
    workspaceId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentResponse[]>(
      {url: `/workspace/${workspaceId}/documents`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPagesQueryKey = (workspaceId: string,) => {
    return [
    `/workspace/${workspaceId}/documents`
    ] as const;
    }

    
export const getGetPagesQueryOptions = <TData = Awaited<ReturnType<typeof getPages>>, TError = ErrorType<Blob>>(workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPagesQueryKey(workspaceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPages>>> = ({ signal }) => getPages(workspaceId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPagesQueryResult = NonNullable<Awaited<ReturnType<typeof getPages>>>
export type GetPagesQueryError = ErrorType<Blob>


export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = ErrorType<Blob>>(
 workspaceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPages>>,
          TError,
          Awaited<ReturnType<typeof getPages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = ErrorType<Blob>>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPages>>,
          TError,
          Awaited<ReturnType<typeof getPages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = ErrorType<Blob>>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = ErrorType<Blob>>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPagesQueryOptions(workspaceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const createPage = (
    workspaceId: string,
    documentRequest: BodyType<DocumentRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentResponse>(
      {url: `/workspace/${workspaceId}/documents`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: documentRequest, signal
    },
      options);
    }
  


export const getCreatePageMutationOptions = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPage>>, TError,{workspaceId: string;data: BodyType<DocumentRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createPage>>, TError,{workspaceId: string;data: BodyType<DocumentRequest>}, TContext> => {

const mutationKey = ['createPage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPage>>, {workspaceId: string;data: BodyType<DocumentRequest>}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  createPage(workspaceId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePageMutationResult = NonNullable<Awaited<ReturnType<typeof createPage>>>
    export type CreatePageMutationBody = BodyType<DocumentRequest>
    export type CreatePageMutationError = ErrorType<Blob>

    export const useCreatePage = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPage>>, TError,{workspaceId: string;data: BodyType<DocumentRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPage>>,
        TError,
        {workspaceId: string;data: BodyType<DocumentRequest>},
        TContext
      > => {
      return useMutation(getCreatePageMutationOptions(options), queryClient);
    }
    
export const listDirectories = (
    workspaceId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DirectoryResponse[]>(
      {url: `/workspace/${workspaceId}/directories`, method: 'GET', signal
    },
      options);
    }
  



export const getListDirectoriesQueryKey = (workspaceId: string,) => {
    return [
    `/workspace/${workspaceId}/directories`
    ] as const;
    }

    
export const getListDirectoriesQueryOptions = <TData = Awaited<ReturnType<typeof listDirectories>>, TError = ErrorType<Blob>>(workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDirectories>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDirectoriesQueryKey(workspaceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDirectories>>> = ({ signal }) => listDirectories(workspaceId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDirectories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDirectoriesQueryResult = NonNullable<Awaited<ReturnType<typeof listDirectories>>>
export type ListDirectoriesQueryError = ErrorType<Blob>


export function useListDirectories<TData = Awaited<ReturnType<typeof listDirectories>>, TError = ErrorType<Blob>>(
 workspaceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDirectories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDirectories>>,
          TError,
          Awaited<ReturnType<typeof listDirectories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDirectories<TData = Awaited<ReturnType<typeof listDirectories>>, TError = ErrorType<Blob>>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDirectories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDirectories>>,
          TError,
          Awaited<ReturnType<typeof listDirectories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDirectories<TData = Awaited<ReturnType<typeof listDirectories>>, TError = ErrorType<Blob>>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDirectories>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListDirectories<TData = Awaited<ReturnType<typeof listDirectories>>, TError = ErrorType<Blob>>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDirectories>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDirectoriesQueryOptions(workspaceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const createDirectory = (
    workspaceId: string,
    directoryRequest: BodyType<DirectoryRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DirectoryResponse>(
      {url: `/workspace/${workspaceId}/directories`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: directoryRequest, signal
    },
      options);
    }
  


export const getCreateDirectoryMutationOptions = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDirectory>>, TError,{workspaceId: string;data: BodyType<DirectoryRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createDirectory>>, TError,{workspaceId: string;data: BodyType<DirectoryRequest>}, TContext> => {

const mutationKey = ['createDirectory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDirectory>>, {workspaceId: string;data: BodyType<DirectoryRequest>}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  createDirectory(workspaceId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDirectoryMutationResult = NonNullable<Awaited<ReturnType<typeof createDirectory>>>
    export type CreateDirectoryMutationBody = BodyType<DirectoryRequest>
    export type CreateDirectoryMutationError = ErrorType<Blob>

    export const useCreateDirectory = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDirectory>>, TError,{workspaceId: string;data: BodyType<DirectoryRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDirectory>>,
        TError,
        {workspaceId: string;data: BodyType<DirectoryRequest>},
        TContext
      > => {
      return useMutation(getCreateDirectoryMutationOptions(options), queryClient);
    }
    
export const movePage = (
    workspaceId: string,
    pageId: string,
    movePageRequest: BodyType<MovePageRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentResponse>(
      {url: `/workspace/${workspaceId}/documents/${pageId}/move`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: movePageRequest, signal
    },
      options);
    }
  


export const getMovePageMutationOptions = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof movePage>>, TError,{workspaceId: string;pageId: string;data: BodyType<MovePageRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof movePage>>, TError,{workspaceId: string;pageId: string;data: BodyType<MovePageRequest>}, TContext> => {

const mutationKey = ['movePage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof movePage>>, {workspaceId: string;pageId: string;data: BodyType<MovePageRequest>}> = (props) => {
          const {workspaceId,pageId,data} = props ?? {};

          return  movePage(workspaceId,pageId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type MovePageMutationResult = NonNullable<Awaited<ReturnType<typeof movePage>>>
    export type MovePageMutationBody = BodyType<MovePageRequest>
    export type MovePageMutationError = ErrorType<Blob>

    export const useMovePage = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof movePage>>, TError,{workspaceId: string;pageId: string;data: BodyType<MovePageRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof movePage>>,
        TError,
        {workspaceId: string;pageId: string;data: BodyType<MovePageRequest>},
        TContext
      > => {
      return useMutation(getMovePageMutationOptions(options), queryClient);
    }
    
export const getPage = (
    workspaceId: string,
    pageId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentResponse>(
      {url: `/workspace/${workspaceId}/documents/${pageId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPageQueryKey = (workspaceId: string,
    pageId: string,) => {
    return [
    `/workspace/${workspaceId}/documents/${pageId}`
    ] as const;
    }

    
export const getGetPageQueryOptions = <TData = Awaited<ReturnType<typeof getPage>>, TError = ErrorType<Blob>>(workspaceId: string,
    pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPageQueryKey(workspaceId,pageId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPage>>> = ({ signal }) => getPage(workspaceId,pageId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId && pageId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPageQueryResult = NonNullable<Awaited<ReturnType<typeof getPage>>>
export type GetPageQueryError = ErrorType<Blob>


export function useGetPage<TData = Awaited<ReturnType<typeof getPage>>, TError = ErrorType<Blob>>(
 workspaceId: string,
    pageId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPage>>,
          TError,
          Awaited<ReturnType<typeof getPage>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPage<TData = Awaited<ReturnType<typeof getPage>>, TError = ErrorType<Blob>>(
 workspaceId: string,
    pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPage>>,
          TError,
          Awaited<ReturnType<typeof getPage>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPage<TData = Awaited<ReturnType<typeof getPage>>, TError = ErrorType<Blob>>(
 workspaceId: string,
    pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPage<TData = Awaited<ReturnType<typeof getPage>>, TError = ErrorType<Blob>>(
 workspaceId: string,
    pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPageQueryOptions(workspaceId,pageId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const deletePage = (
    workspaceId: string,
    pageId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/workspace/${workspaceId}/documents/${pageId}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeletePageMutationOptions = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePage>>, TError,{workspaceId: string;pageId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePage>>, TError,{workspaceId: string;pageId: string}, TContext> => {

const mutationKey = ['deletePage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePage>>, {workspaceId: string;pageId: string}> = (props) => {
          const {workspaceId,pageId} = props ?? {};

          return  deletePage(workspaceId,pageId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePageMutationResult = NonNullable<Awaited<ReturnType<typeof deletePage>>>
    
    export type DeletePageMutationError = ErrorType<Blob>

    export const useDeletePage = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePage>>, TError,{workspaceId: string;pageId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePage>>,
        TError,
        {workspaceId: string;pageId: string},
        TContext
      > => {
      return useMutation(getDeletePageMutationOptions(options), queryClient);
    }
    
export const updatePage = (
    workspaceId: string,
    pageId: string,
    documentRequest: BodyType<DocumentRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentResponse>(
      {url: `/workspace/${workspaceId}/documents/${pageId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: documentRequest, signal
    },
      options);
    }
  


export const getUpdatePageMutationOptions = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePage>>, TError,{workspaceId: string;pageId: string;data: BodyType<DocumentRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePage>>, TError,{workspaceId: string;pageId: string;data: BodyType<DocumentRequest>}, TContext> => {

const mutationKey = ['updatePage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePage>>, {workspaceId: string;pageId: string;data: BodyType<DocumentRequest>}> = (props) => {
          const {workspaceId,pageId,data} = props ?? {};

          return  updatePage(workspaceId,pageId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePageMutationResult = NonNullable<Awaited<ReturnType<typeof updatePage>>>
    export type UpdatePageMutationBody = BodyType<DocumentRequest>
    export type UpdatePageMutationError = ErrorType<Blob>

    export const useUpdatePage = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePage>>, TError,{workspaceId: string;pageId: string;data: BodyType<DocumentRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePage>>,
        TError,
        {workspaceId: string;pageId: string;data: BodyType<DocumentRequest>},
        TContext
      > => {
      return useMutation(getUpdatePageMutationOptions(options), queryClient);
    }
    
export const deleteDirectory = (
    workspaceId: string,
    directoryId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/workspace/${workspaceId}/directories/${directoryId}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getDeleteDirectoryMutationOptions = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDirectory>>, TError,{workspaceId: string;directoryId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDirectory>>, TError,{workspaceId: string;directoryId: string}, TContext> => {

const mutationKey = ['deleteDirectory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDirectory>>, {workspaceId: string;directoryId: string}> = (props) => {
          const {workspaceId,directoryId} = props ?? {};

          return  deleteDirectory(workspaceId,directoryId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDirectoryMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDirectory>>>
    
    export type DeleteDirectoryMutationError = ErrorType<Blob>

    export const useDeleteDirectory = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDirectory>>, TError,{workspaceId: string;directoryId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDirectory>>,
        TError,
        {workspaceId: string;directoryId: string},
        TContext
      > => {
      return useMutation(getDeleteDirectoryMutationOptions(options), queryClient);
    }
    
export const updateDirectory = (
    workspaceId: string,
    directoryId: string,
    directoryRequest: BodyType<DirectoryRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DirectoryResponse>(
      {url: `/workspace/${workspaceId}/directories/${directoryId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: directoryRequest, signal
    },
      options);
    }
  


export const getUpdateDirectoryMutationOptions = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDirectory>>, TError,{workspaceId: string;directoryId: string;data: BodyType<DirectoryRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDirectory>>, TError,{workspaceId: string;directoryId: string;data: BodyType<DirectoryRequest>}, TContext> => {

const mutationKey = ['updateDirectory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDirectory>>, {workspaceId: string;directoryId: string;data: BodyType<DirectoryRequest>}> = (props) => {
          const {workspaceId,directoryId,data} = props ?? {};

          return  updateDirectory(workspaceId,directoryId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateDirectoryMutationResult = NonNullable<Awaited<ReturnType<typeof updateDirectory>>>
    export type UpdateDirectoryMutationBody = BodyType<DirectoryRequest>
    export type UpdateDirectoryMutationError = ErrorType<Blob>

    export const useUpdateDirectory = <TError = ErrorType<Blob>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDirectory>>, TError,{workspaceId: string;directoryId: string;data: BodyType<DirectoryRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDirectory>>,
        TError,
        {workspaceId: string;directoryId: string;data: BodyType<DirectoryRequest>},
        TContext
      > => {
      return useMutation(getUpdateDirectoryMutationOptions(options), queryClient);
    }
