/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const getSnapshotParams = zod.object({
  "documentId": zod.string().uuid()
})


export const saveSnapshotParams = zod.object({
  "documentId": zod.string().uuid()
})

export const saveSnapshotBody = zod.object({
  "version": zod.number().optional(),
  "schemaVersion": zod.number().optional(),
  "generatedAt": zod.string().datetime({}).optional(),
  "updatedBy": zod.string().uuid().optional(),
  "source": zod.string().optional(),
  "content": zod.object({
  "type": zod.string(),
  "content": zod.array(zod.unknown()).optional(),
  "attrs": zod.string().optional(),
  "marks": zod.string().optional(),
  "text": zod.string().optional()
}).optional()
})


export const getPagesParams = zod.object({
  "workspaceId": zod.string().uuid()
})


export const createPageParams = zod.object({
  "workspaceId": zod.string().uuid()
})




export const createPageBody = zod.object({
  "title": zod.string().min(1),
  "icon": zod.string().optional()
})


export const getPageParams = zod.object({
  "pageId": zod.string().uuid(),
  "workspaceId": zod.string().uuid()
})


export const deletePageParams = zod.object({
  "pageId": zod.string().uuid(),
  "workspaceId": zod.string().uuid()
})


export const updatePageParams = zod.object({
  "pageId": zod.string().uuid(),
  "workspaceId": zod.string().uuid()
})




export const updatePageBody = zod.object({
  "title": zod.string().min(1),
  "icon": zod.string().optional()
})
