/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const GetSnapshotParams = zod.object({
  "documentId": zod.uuid()
})

export const GetSnapshotResponse = zod.object({
  "version": zod.number().optional(),
  "schemaVersion": zod.number().optional(),
  "generatedAt": zod.iso.datetime({}).optional(),
  "updatedBy": zod.uuid().optional(),
  "source": zod.string().optional(),
  "contentJson": zod.string().optional()
})


export const SaveSnapshotParams = zod.object({
  "documentId": zod.uuid()
})

export const SaveSnapshotBody = zod.object({
  "version": zod.number().optional(),
  "schemaVersion": zod.number().optional(),
  "generatedAt": zod.iso.datetime({}).optional(),
  "updatedBy": zod.uuid().optional(),
  "source": zod.string().optional(),
  "content": zod.object({
  "type": zod.string(),
  "content": zod.array(zod.unknown()).optional(),
  "attrs": zod.string().optional(),
  "marks": zod.string().optional(),
  "text": zod.string().optional()
}).optional()
})


export const GetPagesParams = zod.object({
  "workspaceId": zod.uuid()
})

export const GetPagesResponseItem = zod.object({
  "id": zod.uuid(),
  "workspaceId": zod.uuid(),
  "title": zod.string(),
  "icon": zod.string(),
  "directoryId": zod.uuid().optional(),
  "sortOrder": zod.number().optional(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})
export const GetPagesResponse = zod.array(GetPagesResponseItem)


export const CreatePageParams = zod.object({
  "workspaceId": zod.uuid()
})




export const CreatePageBody = zod.object({
  "title": zod.string().min(1),
  "icon": zod.string().optional()
})

export const CreatePageResponse = zod.object({
  "id": zod.uuid(),
  "workspaceId": zod.uuid(),
  "title": zod.string(),
  "icon": zod.string(),
  "directoryId": zod.uuid().optional(),
  "sortOrder": zod.number().optional(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})


export const ListDirectoriesParams = zod.object({
  "workspaceId": zod.uuid()
})

export const ListDirectoriesResponseItem = zod.object({
  "id": zod.uuid().optional(),
  "workspaceId": zod.uuid().optional(),
  "parentId": zod.uuid().optional(),
  "name": zod.string().optional(),
  "sortOrder": zod.number().optional(),
  "createdAt": zod.iso.datetime({}).optional()
})
export const ListDirectoriesResponse = zod.array(ListDirectoriesResponseItem)


export const CreateDirectoryParams = zod.object({
  "workspaceId": zod.uuid()
})

export const createDirectoryBodyNameMin = 0;
export const createDirectoryBodyNameMax = 255;



export const CreateDirectoryBody = zod.object({
  "name": zod.string().min(createDirectoryBodyNameMin).max(createDirectoryBodyNameMax),
  "parentId": zod.uuid().optional(),
  "sortOrder": zod.number().optional()
})

export const CreateDirectoryResponse = zod.object({
  "id": zod.uuid().optional(),
  "workspaceId": zod.uuid().optional(),
  "parentId": zod.uuid().optional(),
  "name": zod.string().optional(),
  "sortOrder": zod.number().optional(),
  "createdAt": zod.iso.datetime({}).optional()
})


export const MovePageParams = zod.object({
  "pageId": zod.uuid(),
  "workspaceId": zod.uuid()
})

export const MovePageBody = zod.object({
  "directoryId": zod.uuid().optional(),
  "sortOrder": zod.number().optional()
})

export const MovePageResponse = zod.object({
  "id": zod.uuid(),
  "workspaceId": zod.uuid(),
  "title": zod.string(),
  "icon": zod.string(),
  "directoryId": zod.uuid().optional(),
  "sortOrder": zod.number().optional(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})


export const GetPageParams = zod.object({
  "pageId": zod.uuid(),
  "workspaceId": zod.uuid()
})

export const GetPageResponse = zod.object({
  "id": zod.uuid(),
  "workspaceId": zod.uuid(),
  "title": zod.string(),
  "icon": zod.string(),
  "directoryId": zod.uuid().optional(),
  "sortOrder": zod.number().optional(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})


export const DeletePageParams = zod.object({
  "pageId": zod.uuid(),
  "workspaceId": zod.uuid()
})


export const UpdatePageParams = zod.object({
  "pageId": zod.uuid(),
  "workspaceId": zod.uuid()
})




export const UpdatePageBody = zod.object({
  "title": zod.string().min(1),
  "icon": zod.string().optional()
})

export const UpdatePageResponse = zod.object({
  "id": zod.uuid(),
  "workspaceId": zod.uuid(),
  "title": zod.string(),
  "icon": zod.string(),
  "directoryId": zod.uuid().optional(),
  "sortOrder": zod.number().optional(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})


export const DeleteDirectoryParams = zod.object({
  "workspaceId": zod.uuid(),
  "directoryId": zod.uuid()
})


export const UpdateDirectoryParams = zod.object({
  "workspaceId": zod.uuid(),
  "directoryId": zod.uuid()
})

export const updateDirectoryBodyNameMin = 0;
export const updateDirectoryBodyNameMax = 255;



export const UpdateDirectoryBody = zod.object({
  "name": zod.string().min(updateDirectoryBodyNameMin).max(updateDirectoryBodyNameMax),
  "parentId": zod.uuid().optional(),
  "sortOrder": zod.number().optional()
})

export const UpdateDirectoryResponse = zod.object({
  "id": zod.uuid().optional(),
  "workspaceId": zod.uuid().optional(),
  "parentId": zod.uuid().optional(),
  "name": zod.string().optional(),
  "sortOrder": zod.number().optional(),
  "createdAt": zod.iso.datetime({}).optional()
})
