/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const getPagesParams = zod.object({
  "workspaceId": zod.string().uuid()
})


export const createPageParams = zod.object({
  "workspaceId": zod.string().uuid()
})




export const createPageBody = zod.object({
  "title": zod.string().min(1),
  "icon": zod.string().optional()
})


export const snapshotParams = zod.object({
  "documentId": zod.string().uuid()
})

export const snapshotBody = zod.object({
  "version": zod.number().optional(),
  "blocks": zod.array(zod.object({
    "id": zod.string().uuid().optional(),
    "parentId": zod.string().uuid().optional(),
    "type": zod.string().optional(),
    "position": zod.string().optional(),
    "content": zod.unknown().optional(),
    "attrs": zod.unknown().optional()
  })).optional()
})


export const getPageParams = zod.object({
  "pageId": zod.string().uuid(),
  "workspaceId": zod.string().uuid()
})


export const deletePageParams = zod.object({
  "pageId": zod.string().uuid(),
  "workspaceId": zod.string().uuid()
})


export const updatePageParams = zod.object({
  "pageId": zod.string().uuid(),
  "workspaceId": zod.string().uuid()
})




export const updatePageBody = zod.object({
  "title": zod.string().min(1),
  "icon": zod.string().optional()
})


export const getTreeParams = zod.object({
  "id": zod.string().uuid(),
  "workspaceId": zod.string()
})
