/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

/**
 * @summary Verify user using code
 */



export const verifyUserBody = zod.object({
  "email": zod.string().email().min(1)
})


/**
 * @summary Register user using email/password
 */



export const createUserBodyPasswordRegExp = new RegExp('^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$');


export const createUserBody = zod.object({
  "email": zod.string().email().min(1),
  "password": zod.string().min(1).regex(createUserBodyPasswordRegExp)
})


/**
 * @summary Generate Token on user login
 */



export const loginBodyPasswordRegExp = new RegExp('^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$');


export const loginBody = zod.object({
  "email": zod.string().email().min(1),
  "password": zod.string().min(1).regex(loginBodyPasswordRegExp)
})


/**
 * @summary Validate Token
 */
export const validateTokenHeader = zod.object({
  "Authorization": zod.string()
})
