/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

/**
 * @summary Register user using email/password
 */



export const createUserBodyPasswordRegExp = new RegExp('^(?=.\*[a-z])(?=.\*[A-Z])(?=.\*\\d)(?=.\*[@$!%\*?&])[A-Za-z\\d@$!%\*?&]{8,}$');


export const CreateUserBody = zod.object({
  "email": zod.email().min(1),
  "password": zod.string().min(1).regex(createUserBodyPasswordRegExp)
})


/**
 * Invalidates the session or token and logs the user out
 * @summary Logout
 */
export const LogoutHeader = zod.object({
  "Authorization": zod.string()
})


/**
 * @summary Generate Token on user login
 */



export const loginBodyPasswordRegExp = new RegExp('^(?=.\*[a-z])(?=.\*[A-Z])(?=.\*\\d)(?=.\*[@$!%\*?&])[A-Za-z\\d@$!%\*?&]{8,}$');


export const LoginBody = zod.object({
  "email": zod.email().min(1),
  "password": zod.string().min(1).regex(loginBodyPasswordRegExp)
})


/**
 * @summary Reset password using code
 */




export const resetPasswordBodyNewPasswordRegExp = new RegExp('^(?=.\*[a-z])(?=.\*[A-Z])(?=.\*\\d)(?=.\*[@$!%\*?&])[A-Za-z\\d@$!%\*?&]{8,}$');


export const ResetPasswordBody = zod.object({
  "email": zod.email().min(1),
  "code": zod.string().min(1),
  "newPassword": zod.string().min(1).regex(resetPasswordBodyNewPasswordRegExp)
})


/**
 * @summary Initiate password reset
 */



export const InitiatePasswordResetBody = zod.object({
  "email": zod.email().min(1)
})
