apiVersion: v1
data:
  SCALAR_ENABLED: "false"
  SPRING_GRPC_SERVER_PORT: "9090"
  SPRING_JPA_HIBERNATE_DDL_AUTO: none
  SPRING_SQL_INIT_MODE: never
  JAVA_TOOL_OPTIONS: "-XX:ReservedCodeCacheSize=64m -XX:MaxDirectMemorySize=64m -XX:+UseZGC --enable-native-access=ALL-UNNAMED"
  OTEL_JAVAAGENT_ENABLED: "true"
  BPL_JVM_HEAD_ROOM: "10"
  BPL_JVM_THREAD_COUNT: "20"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-k8s-monitoring-alloy-receiver.observability.svc.cluster.local:4318
  OTEL_SERVICE_NAME: workspace-service
  OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
kind: ConfigMap
metadata:
  name: workspace-service-configmap
