apiVersion: v1
data:
  AWS_REGION: ap-south-1
  SCALAR_ENABLED: "false"
  SPRING_FLYWAY_ENABLED: "false"
  SPRING_GRPC_SERVER_PORT: "9090"
  SPRING_SQL_INIT_MODE: never
  JAVA_TOOL_OPTIONS: "-XX:ReservedCodeCacheSize=64m -XX:MaxDirectMemorySize=64m -XX:+UseZGC --enable-native-access=ALL-UNNAMED"
  OTEL_JAVAAGENT_ENABLED: "true"
  BPL_JVM_HEAD_ROOM: "10"
  BPL_JVM_THREAD_COUNT: "20"
  SPRING_MAIN_LAZY_INITIALIZATION: "false"
  SPRING_REDIS_HOST: "192.168.29.29"
  SPRING_REDIS_PORT: "6379"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-k8s-monitoring-alloy-receiver.observability.svc.cluster.local:4318
  OTEL_SERVICE_NAME: user-service
  OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
kind: ConfigMap
metadata:
  name: user-service-configmap
