apiVersion: v1
kind: Secret
metadata:
  name: ai-service-secrets
  namespace: apps
type: Opaque
data:
  # Base64 encoded values
  SPRING_AI_OPENAI_API_KEY: <OPENAI_API_KEY>
  SPRING_DATASOURCE_PASSWORD: <PASSWORD>
  SPRING_DATASOURCE_USERNAME: <USERNAME>
  SPRING_DATASOURCE_URL: <URL>
