apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: auth-service-secrets
data:
  # Base64 encoded values
  JWT_SECRET: <JWT_SECRET>
  SPRING_DATASOURCE_PASSWORD: <PASSWORD>
  SPRING_DATASOURCE_USERNAME: <USERNAME>
  SPRING_DATA_REDIS_HOST: <REDIS_HOST>
  SPRING_DATASOURCE_URL: <URL>
